keycloak-client:
  serverUrl: ${KEYCLOAK_API_SERVER_URL}
  realm: ${KEYCLOAK_API_REALM}
  username: ${KEYCLOAK_API_USERNAME}
  password: ${KEYCLOAK_API_PASSWORD}
  clientId: ${KEYCLOAK_API_CLIENT_ID}
  clientSecret: ${KEYCLOAK_API_CLIENT_SECRET}

keycloak-resources:
  authorities:
    User:
      groupId: 0d3fecee-6dcc-4b1b-92ec-8410ed7dd780
    Admin:
      groupId: dd91fd2a-ba4f-491e-8953-2d2bfc4e4aa5