permissions:
  extendedClaims: [ ]
  policies:
    # Users
    BrowseUser:
      roles:
        - Admin
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: false
    EditUser:
      roles:
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DeleteUser:
      roles:
        - Admin
      claims: [ ]
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false

    # ViewPage Permissions
    ViewHomePage:
      roles: [ ]
      clients: [ ]
      allowAnonymous: true
      allowAuthenticated: true
    ViewFaqPage:
      roles:
        - User
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewEwbPage:
      roles:
        - User
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewClassifyPage:
      roles:
        - User
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    ViewUsersPage:
      roles:
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
    DownloadReport:
      roles:
        - User
        - Admin
      clients: [ ]
      allowAnonymous: false
      allowAuthenticated: false
